"""Compute price spread ratios from all_platforms.csv for router.py constants.

Usage:
    python scripts/compute_router_constants.py

Reads data/cleaned/all_platforms.csv, computes p25/p50 and p75/p50 ratios
for each (category, platform) pair, and prints a Python dict ready to paste
into models/router.py.  Re-run after any data refresh to keep constants current.
"""

import pandas as pd
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "cleaned" / "all_platforms.csv"
MIN_ROWS = 20  # fall back to platform-wide ratio if fewer rows


def main():
    df = pd.read_csv(DATA_PATH)
    df = df.dropna(subset=["final_sale_price"])
    df = df[df["final_sale_price"] >= 1.0]

    # --- Per-category × platform ratios ---
    ratios = {}
    for (cat, plat), grp in df.groupby(["item_category", "platform"]):
        p25 = grp["final_sale_price"].quantile(0.25)
        p50 = grp["final_sale_price"].quantile(0.50)
        p75 = grp["final_sale_price"].quantile(0.75)
        if p50 == 0:
            continue
        low = round(p25 / p50, 3)
        high = round(p75 / p50, 3)
        ratios[(cat, plat)] = {"low": low, "high": high, "n": len(grp)}

    # --- Platform-wide fallbacks ---
    fallbacks = {}
    for plat, grp in df.groupby("platform"):
        p25 = grp["final_sale_price"].quantile(0.25)
        p50 = grp["final_sale_price"].quantile(0.50)
        p75 = grp["final_sale_price"].quantile(0.75)
        if p50 == 0:
            continue
        fallbacks[plat] = {"low": round(p25 / p50, 3), "high": round(p75 / p50, 3)}

    # --- Print Python constant ---
    print("# Auto-generated by scripts/compute_router_constants.py")
    print("# Re-run after data refresh: python scripts/compute_router_constants.py")
    print()

    print("PRICE_SPREAD_RATIOS = {")
    for (cat, plat), vals in sorted(ratios.items()):
        note = "" if vals["n"] >= MIN_ROWS else f"  # n={vals['n']}, below {MIN_ROWS}-row threshold — consider fallback"
        print(f'    ("{cat}", "{plat}"): {{"low": {vals["low"]}, "high": {vals["high"]}}},{note}')
    print("}")

    print()
    print("PRICE_SPREAD_FALLBACKS = {")
    for plat, vals in sorted(fallbacks.items()):
        print(f'    "{plat}": {{"low": {vals["low"]}, "high": {vals["high"]}}},')
    print("}")


if __name__ == "__main__":
    main()
