"""Platform routing algorithm for ListIQ.

Given an item description, predicts optimal platform, price tiers, net profit,
sell-through estimates, and a Worth It verdict.

Public API:
    recommend_listing(item: dict) -> dict

The returned dict matches the locked frontend JSON contract exactly.
"""

import math
import re
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Model loading (once at module level)
# ---------------------------------------------------------------------------

_MODELS_DIR = Path(__file__).resolve().parent

_model = joblib.load(_MODELS_DIR / "pricing_model.joblib")
_config = joblib.load(_MODELS_DIR / "feature_config.joblib")

LUXURY_BRANDS = _config["LUXURY_BRANDS"]
PREMIUM_BRANDS = _config["PREMIUM_BRANDS"]
TOP_30_BRANDS = _config["TOP_30_BRANDS"]
CONDITION_MAP = _config["CONDITION_MAP"]
CATEGORICAL_FEATURES = _config["CATEGORICAL_FEATURES"]
NUMERIC_FEATURES = _config["NUMERIC_FEATURES"]
ALL_FEATURES = _config["ALL_FEATURES"]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PLATFORMS = ["eBay", "Poshmark", "Depop"]

VALID_CATEGORIES = [
    "blazer", "crossbody bag", "denim jacket", "handbag",
    "leather jacket", "midi dress", "sneakers", "vintage t-shirt",
]

# Three-way categories (have Depop training data)
THREE_WAY_CATEGORIES = {"denim jacket", "handbag", "midi dress", "sneakers"}

PLATFORM_FEES = {"eBay": 0.13, "Poshmark": 0.20, "Depop": 0.10}
SHIPPING_COST = 5.99
SELLER_TIME_MINUTES = 35

HOURLY_RATE_THRESHOLDS = {"worth_it": 20, "marginal": 10}

# Poshmark sell-velocity medians (real data from EDA notebook)
POSHMARK_VELOCITY_DAYS = {
    "vintage t-shirt": 20,
    "handbag": 22,
    "sneakers": 23,
    "midi dress": 23,
    "leather jacket": 33,
    "blazer": 35,
    "crossbody bag": 38,
    "denim jacket": 39,
}

# Platform velocity multipliers applied to Poshmark baseline.
# eBay 0.75x = faster (larger buyer pool, strong search/SEO).
# Depop 1.1x = slightly slower (narrower Gen Z audience, lower traffic).
# These are documented assumptions, not measured from data.
PLATFORM_VELOCITY_MULTIPLIERS = {"eBay": 0.75, "Poshmark": 1.0, "Depop": 1.1}

# Auto-generated by scripts/compute_router_constants.py
# Re-run after data refresh: python scripts/compute_router_constants.py
PRICE_SPREAD_RATIOS = {
    ("blazer", "Poshmark"): {"low": 0.552, "high": 1.603},
    ("blazer", "eBay"): {"low": 0.536, "high": 1.796},
    ("crossbody bag", "Poshmark"): {"low": 0.478, "high": 2.107},
    ("crossbody bag", "eBay"): {"low": 0.462, "high": 2.308},
    ("denim jacket", "Depop"): {"low": 0.641, "high": 1.714},
    ("denim jacket", "Poshmark"): {"low": 0.682, "high": 1.545},
    ("denim jacket", "eBay"): {"low": 0.425, "high": 1.8},
    ("handbag", "Depop"): {"low": 0.786, "high": 2.143},
    ("handbag", "Poshmark"): {"low": 0.421, "high": 2.368},
    ("handbag", "eBay"): {"low": 0.431, "high": 2.309},
    ("leather jacket", "Poshmark"): {"low": 0.579, "high": 1.737},
    ("leather jacket", "eBay"): {"low": 0.448, "high": 2.333},
    ("midi dress", "Depop"): {"low": 0.548, "high": 1.808},
    ("midi dress", "Poshmark"): {"low": 0.69, "high": 1.526},
    ("midi dress", "eBay"): {"low": 0.476, "high": 1.905},
    ("sneakers", "Depop"): {"low": 0.5, "high": 2.275},
    ("sneakers", "Poshmark"): {"low": 0.714, "high": 1.429},
    ("sneakers", "eBay"): {"low": 0.583, "high": 1.583},
    ("vintage t-shirt", "Poshmark"): {"low": 0.556, "high": 1.556},
    ("vintage t-shirt", "eBay"): {"low": 0.54, "high": 1.667},
}

PRICE_SPREAD_FALLBACKS = {
    "Depop": {"low": 0.56, "high": 2.0},
    "Poshmark": {"low": 0.667, "high": 2.0},
    "eBay": {"low": 0.513, "high": 2.125},
}

# Regex patterns (replicated from notebook)
SIZE_PATTERN = re.compile(
    r"\b(?:XXS|XS|S|M|L|XL|XXL|XXXL|\d{1,2}(?:\.\d)?)\b", re.IGNORECASE
)
NWT_PATTERN = re.compile(r"\b(?:NWT|BNWT|new with tags)\b", re.IGNORECASE)


# ---------------------------------------------------------------------------
# Feature engineering (replicated from notebooks/02_pricing_model.ipynb)
# ---------------------------------------------------------------------------

def _get_brand_tier(brand: str) -> str:
    if brand in LUXURY_BRANDS:
        return "luxury"
    if brand in PREMIUM_BRANDS:
        return "premium"
    if brand != "Unknown":
        return "known"
    return "unknown"


def _engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Build all modeling features from raw inputs."""
    out = df.copy()

    # Brand features
    out["brand"] = out["brand"].fillna("Unknown")
    out["brand_tier"] = out["brand"].apply(_get_brand_tier)
    out["brand_top30"] = out["brand"].apply(
        lambda b: b if b in TOP_30_BRANDS else "Other"
    )

    # Condition features
    out["condition"] = out["condition"].fillna("Unknown")
    out["condition_ordinal"] = (
        out["condition"].map(CONDITION_MAP).fillna(0).astype(int)
    )

    # Title features
    title_lower = out["title"].str.lower()
    out["title_length"] = out["title"].str.len()
    out["title_word_count"] = out["title"].str.split().str.len()
    out["title_has_brand"] = (
        (out["brand"] != "Unknown")
        & out.apply(lambda r: r["brand"].lower() in r["title"].lower(), axis=1)
    ).astype(int)
    out["title_has_size"] = title_lower.str.contains(SIZE_PATTERN).astype(int)
    out["title_has_vintage"] = title_lower.str.contains("vintage").astype(int)
    out["title_has_nwt"] = title_lower.str.contains(NWT_PATTERN).astype(int)

    # Interaction features
    out["platform_category"] = out["platform"] + "_" + out["item_category"]

    return out


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _predict_price(platform: str, category: str, brand: str,
                   condition: str, title: str) -> float:
    """Predict final sale price for an item on a single platform."""
    row = pd.DataFrame([{
        "platform": platform,
        "item_category": category,
        "brand": brand,
        "condition": condition,
        "title": title,
    }])
    row = _engineer_features(row)
    pred_log = _model.predict(row[ALL_FEATURES])
    return float(np.clip(np.expm1(pred_log[0]), 1.0, None))


def _compute_price_tiers(predicted_price: float, category: str,
                         platform: str) -> dict:
    """Compute fast_sale / balanced / max_revenue price tiers."""
    key = (category, platform)
    ratios = PRICE_SPREAD_RATIOS.get(key, PRICE_SPREAD_FALLBACKS.get(platform))
    if ratios is None:
        ratios = {"low": 0.75, "high": 1.5}

    return {
        "fast_sale": round(predicted_price * ratios["low"]),
        "balanced": round(predicted_price),
        "max_revenue": round(predicted_price * ratios["high"]),
    }


def _estimate_velocity(category: str, platform: str) -> dict:
    """Estimate days_to_sale and sell_probability_30d."""
    base_days = POSHMARK_VELOCITY_DAYS.get(category, 30)
    multiplier = PLATFORM_VELOCITY_MULTIPLIERS.get(platform, 1.0)
    days = max(1, round(base_days * multiplier))
    sell_prob = min(1.0, round(30 / days, 2))
    return {
        "estimated_days_to_sale": days,
        "sell_probability_30d": sell_prob,
    }


def _compute_net_profit(price_tiers: dict, platform: str) -> dict:
    """Compute net profit for each price tier after fees and shipping."""
    fee = PLATFORM_FEES[platform]
    return {
        tier: round(price * (1 - fee) - SHIPPING_COST, 2)
        for tier, price in price_tiers.items()
    }


def _compute_raw_fit_score(net_profit_balanced: float, sell_prob: float,
                           days_to_sale: int) -> float:
    """Raw fit score: expected value adjusted for time.

    Formula: (net_profit × sell_probability) / sqrt(days_to_sale)
    sqrt() penalizes slow platforms without annihilating them.
    """
    if days_to_sale <= 0 or net_profit_balanced <= 0:
        return 0.0
    return (net_profit_balanced * sell_prob) / math.sqrt(days_to_sale)


def _generate_reasoning(rec: dict, all_recs: list[dict]) -> str:
    """Generate a templated reasoning string for a recommendation."""
    platform = rec["platform"]
    category = rec["_category"]
    rank = rec["rank"]
    days = rec["estimated_days_to_sale"]
    net_balanced = rec["net_profit"]["balanced"]
    fee_pct = int(PLATFORM_FEES[platform] * 100)

    others = [r for r in all_recs if r["platform"] != platform]

    depop_note = ""
    if platform == "Depop":
        depop_note = " (listed-price proxy)"
    if platform == "Depop" and category not in THREE_WAY_CATEGORIES:
        depop_note = " (limited training data — listed-price proxy)"

    if rank == 1:
        # Find advantage over runner-up
        if others:
            runner_up = others[0]
            profit_diff = net_balanced - runner_up["net_profit"]["balanced"]
            days_diff = runner_up["estimated_days_to_sale"] - days

            parts = []
            if profit_diff > 1:
                parts.append(f"nets ${profit_diff:.0f} more than {runner_up['platform']}")
            if days_diff > 2:
                parts.append(f"estimated {days_diff} days faster")

            if parts:
                advantage = " and ".join(parts)
                return (
                    f"{category.title()}s {advantage} on {platform} "
                    f"after {fee_pct}% fee{depop_note}"
                )

        return (
            f"Best overall value for {category}s on {platform} — "
            f"${net_balanced:.0f} net profit in ~{days} days{depop_note}"
        )

    # Rank 2-3: highlight differentiator and tradeoff
    best = all_recs[0]
    profit_diff = best["net_profit"]["balanced"] - net_balanced

    if days < best["estimated_days_to_sale"]:
        days_advantage = best["estimated_days_to_sale"] - days
        return (
            f"{platform} offers faster sell-through (~{days} days, "
            f"{days_advantage} days quicker) but {fee_pct}% fee "
            f"leaves ${profit_diff:.0f} less net profit{depop_note}"
        )

    if fee_pct < int(PLATFORM_FEES[best["platform"]] * 100):
        return (
            f"{platform} has lower fees ({fee_pct}%) but estimated net profit "
            f"is ${profit_diff:.0f} less than {best['platform']}{depop_note}"
        )

    return (
        f"{platform} is a viable alternative at ${net_balanced:.0f} net profit "
        f"in ~{days} days ({fee_pct}% fee){depop_note}"
    )


def _build_worth_it(recommendations: list[dict]) -> dict:
    """Build the worth_it verdict from the best recommendation."""
    best = recommendations[0]
    best_net = best["net_profit"]["balanced"]
    hourly = best["effective_hourly_rate"]
    platform = best["platform"]

    fast_net = best["net_profit"]["fast_sale"]
    max_net = best["net_profit"]["max_revenue"]

    if hourly >= HOURLY_RATE_THRESHOLDS["worth_it"]:
        verdict = True
        explanation = (
            f"Worth listing — estimated ${fast_net:.0f}-{max_net:.0f} net profit "
            f"on {platform} after fees and shipping"
        )
    elif hourly >= HOURLY_RATE_THRESHOLDS["marginal"]:
        verdict = "marginal"
        explanation = (
            f"Marginal — estimated ${best_net:.0f} net profit on {platform}, "
            f"but effective hourly rate (${hourly:.0f}/hr) is below $20"
        )
    else:
        verdict = False
        explanation = (
            f"Not worth listing — estimated ${best_net:.0f} net profit on "
            f"{platform} yields only ${hourly:.0f}/hr effective rate"
        )

    return {
        "verdict": verdict,
        "best_net_profit": best_net,
        "best_platform": platform,
        "effective_hourly_rate": hourly,
        "explanation": explanation,
    }


def _synthesize_title(category: str, brand: str, size: str | None,
                      condition: str, color: str | None) -> str:
    """Build a pseudo-title from item attributes for title-based features.

    size and color: used for title synthesis only; not direct model features.
    """
    parts = [brand]
    if size:
        parts.append(size)
    if condition and condition != "Unknown":
        parts.append(condition)
    if color:
        parts.append(color)
    parts.append(category)
    return " ".join(parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def recommend_listing(item: dict) -> dict:
    """Generate platform recommendations for a resale item.

    Args:
        item: dict with keys:
            - category (str, required): one of 8 valid categories
            - brand (str, optional): brand name, defaults to "Unknown"
            - condition (str, optional): defaults to "Unknown"
            - size (str, optional): display + title synthesis
            - color (str, optional): display + title synthesis
            - estimated_retail (float, optional): display-only

    Returns:
        dict matching the locked frontend JSON contract.
    """
    # --- Input validation ---
    category = item.get("category", "").lower().strip()
    if category not in VALID_CATEGORIES:
        raise ValueError(
            f"Unknown category '{category}'. "
            f"Valid: {', '.join(VALID_CATEGORIES)}"
        )

    brand = item.get("brand") or "Unknown"
    condition = item.get("condition") or "Unknown"
    size = item.get("size")
    color = item.get("color")
    estimated_retail = item.get("estimated_retail")

    title = _synthesize_title(category, brand, size, condition, color)

    # --- Per-platform calculations ---
    raw_recs = []
    for platform in PLATFORMS:
        predicted_price = _predict_price(platform, category, brand,
                                         condition, title)
        price_tiers = _compute_price_tiers(predicted_price, category, platform)
        velocity = _estimate_velocity(category, platform)
        net_profit = _compute_net_profit(price_tiers, platform)
        raw_score = _compute_raw_fit_score(
            net_profit["balanced"],
            velocity["sell_probability_30d"],
            velocity["estimated_days_to_sale"],
        )
        hourly_rate = round(
            net_profit["balanced"] / (SELLER_TIME_MINUTES / 60), 2
        )

        raw_recs.append({
            "platform": platform,
            "price_tiers": price_tiers,
            "platform_fee_pct": PLATFORM_FEES[platform],
            "estimated_shipping": SHIPPING_COST,
            "net_profit": net_profit,
            "estimated_time_minutes": SELLER_TIME_MINUTES,
            "effective_hourly_rate": round(hourly_rate, 2),
            "sell_probability_30d": velocity["sell_probability_30d"],
            "estimated_days_to_sale": velocity["estimated_days_to_sale"],
            "_raw_score": raw_score,
            "_category": category,
        })

    # --- Normalize fit scores to 0-10 ---
    max_score = max(r["_raw_score"] for r in raw_recs)
    for rec in raw_recs:
        if max_score > 0:
            rec["fit_score"] = round(10 * rec["_raw_score"] / max_score, 1)
        else:
            rec["fit_score"] = 0.0

    # --- Rank by fit_score descending ---
    raw_recs.sort(key=lambda r: r["fit_score"], reverse=True)
    for i, rec in enumerate(raw_recs):
        rec["rank"] = i + 1

    # --- Generate reasoning ---
    for rec in raw_recs:
        rec["reasoning"] = _generate_reasoning(rec, raw_recs)

    # --- Build worth_it ---
    worth_it = _build_worth_it(raw_recs)

    # --- Assemble response (strip internal keys) ---
    recommendations = []
    for rec in raw_recs:
        recommendations.append({
            "platform": rec["platform"],
            "rank": rec["rank"],
            "fit_score": rec["fit_score"],
            "price_tiers": rec["price_tiers"],
            "platform_fee_pct": rec["platform_fee_pct"],
            "estimated_shipping": rec["estimated_shipping"],
            "net_profit": rec["net_profit"],
            "estimated_time_minutes": rec["estimated_time_minutes"],
            "effective_hourly_rate": rec["effective_hourly_rate"],
            "sell_probability_30d": rec["sell_probability_30d"],
            "estimated_days_to_sale": rec["estimated_days_to_sale"],
            "reasoning": rec["reasoning"],
        })

    return {
        "item": {
            "category": category,
            "brand": brand,
            "size": size,
            "condition": condition,
            "color": color,
            "estimated_retail": estimated_retail,
        },
        "recommendations": recommendations,
        "worth_it": worth_it,
    }
